In [ ]:
import nltk

In [ ]:
import tensorflow as tf

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train = pd.read_csv('/content/train.csv', error_bad_lines=False, engine='python')

Skipping line 13535: field larger than field limit (131072)
Skipping line 15613: unexpected end of data
Skipping line 13541: Expected 5 fields in line 13541, saw 6


In [ ]:
train.head()

id  ... label
0  0  ...   1.0
1  1  ...   0.0
2  2  ...   1.0
3  3  ...   1.0
4  4  ...   1.0

[5 rows x 5 columns]

In [ ]:
train.shape

(15609, 5)

In [ ]:
train.isnull().sum()

id           0
title      409
author    1499
text        48
label       16
dtype: int64

In [ ]:
train.dropna(inplace=True)

In [ ]:
train.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [ ]:
message = train.copy()

In [ ]:
message.reset_index(inplace=True)

In [ ]:
message.head(15)

index  id  ...                                               text label
0       0   0  ...  House Dem Aide: We Didn’t Even See Comey’s Let...   1.0
1       1   1  ...  Ever get the feeling your life circles the rou...   0.0
2       2   2  ...  Why the Truth Might Get You Fired October 29, ...   1.0
3       3   3  ...  Videos 15 Civilians Killed In Single US Airstr...   1.0
4       4   4  ...  Print \nAn Iranian woman has been sentenced to...   1.0
5       5   5  ...  In these trying times, Jackie Mason is the Voi...   0.0
6       7   7  ...  PARIS  —   France chose an idealistic, traditi...   0.0
7       9   9  ...  A week before Michael T. Flynn resigned as nat...   0.0
8      10  10  ...  Organizing for Action, the activist group that...   0.0
9      11  11  ...  The BBC produced spoof on the “Real Housewives...   0.0
10     12  12  ...  The mystery surrounding The Third Reich and Na...   1.0
11     13  13  ...  Clinton Campaign Demands FBI Affirm Trump's Ru...   1.0
12     14  14  ...  Yes, There Are Paid Government Trolls On Socia...   1.0
13     15  15  ...  Guillermo Barros Schelotto was not the first A...   0.0
14     16  16  ...  The scandal engulfing Wells Fargo toppled its ...   0.0

[15 rows x 6 columns]

In [ ]:
message['title'][5]

'Jackie Mason: Hollywood Would Love Trump if He Bombed North Korea over Lack of Trans Bathrooms (Exclusive Video) - Breitbart'

In [ ]:
message.shape

(13703, 6)

In [ ]:
col1 = message['title']

In [ ]:
import re

In [ ]:
import nltk
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
# importing nltk objects which will be in further use.
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps =  PorterStemmer()

In [ ]:
corpus=[]
for i in range(len(message)):
    review= re.sub('[^a-zA-Z]', ' ', col1[i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if word not in set(stopwords.words('english'))]
    review= ' '.join(review)
    corpus.append(review)

In [ ]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [ ]:
corpus[5]

'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart'

In [ ]:
len(corpus)

13703

# Word Embedding

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
voc_size= 1000

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 

In [ ]:
print(onehot_repr)

[[763, 214, 748, 90, 324, 182, 646, 868, 608, 296], [945, 141, 552, 128, 791, 992, 677], [799, 32, 963, 723], [824, 295, 765, 230, 363, 841], [802, 791, 724, 720, 196, 710, 791, 664, 636, 761], [42, 294, 978, 861, 269, 332, 601, 462, 515, 257, 479, 715, 645, 868, 677], [306, 631, 767, 64, 831, 923, 426, 717, 994, 166, 867], [339, 308, 66, 553, 613, 539, 332, 902, 994, 166, 867], [193, 988, 427, 951, 828, 973, 683, 41, 332, 597], [102, 945, 93, 140, 124, 232, 30, 493], [131, 959, 454, 487, 478, 569, 362, 485, 39, 392, 784], [230, 469, 324, 973, 332, 613], [51, 651, 858, 610, 222, 825, 810, 26, 274], [435, 835, 145, 37, 733, 814, 874, 994, 166, 867], [181, 501, 388, 538, 181, 994, 166, 867], [297, 699, 315, 998, 748, 813, 237, 804, 924, 79], [614, 528, 141], [778, 373, 785, 695, 332, 481, 984, 677], [594, 660, 552, 227, 343, 898, 49, 598, 710], [182, 487, 332, 569, 701, 677], [241, 730, 302, 961, 772, 49, 733, 379, 774, 994, 166, 867], [98, 375, 156, 731, 374, 362, 881], [645, 755, 425, 

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import SpatialDropout1D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Bidirectional

In [ ]:
sent_length= 15

In [ ]:
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs[6])

[  0   0   0   0 306 631 767  64 831 923 426 717 994 166 867]


In [ ]:
dim=50

In [ ]:
embedding_vector_features = 50

model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(SpatialDropout1D(0.4))
model.add(Bidirectional(LSTM(200, dropout=0.2)))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 15, 50)            50000     
_________________________________________________________________
spatial_dropout1d (SpatialDr (None, 15, 50)            0         
_________________________________________________________________
bidirectional (Bidirectional (None, 400)               401600    
_________________________________________________________________
flatten (Flatten)            (None, 400)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               51328     
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                

In [ ]:
X = np.array(embedded_docs)

In [ ]:
X.shape

(13703, 15)

In [ ]:
y = message['label'].values

In [109]:
y.shape

(13703,)

Train-Test Split

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [108]:
X_train.shape

(10277, 15)

# LSTM Model

In [111]:
model.fit(X_train,y_train, epochs=7,validation_data=(X_test,y_test), batch_size=32)

Epoch 1/7
322/322 [==============================] - 26s 82ms/step - loss: 0.0504 - accuracy: 0.9816 - val_loss: 0.4418 - val_accuracy: 0.9022
Epoch 2/7
322/322 [==============================] - 26s 82ms/step - loss: 0.0482 - accuracy: 0.9824 - val_loss: 0.4005 - val_accuracy: 0.9019
Epoch 3/7
322/322 [==============================] - 26s 81ms/step - loss: 0.0461 - accuracy: 0.9819 - val_loss: 0.3994 - val_accuracy: 0.8981
Epoch 4/7
322/322 [==============================] - 26s 82ms/step - loss: 0.0413 - accuracy: 0.9839 - val_loss: 0.4840 - val_accuracy: 0.8981
Epoch 5/7
322/322 [==============================] - 26s 81ms/step - loss: 0.0342 - accuracy: 0.9868 - val_loss: 0.5058 - val_accuracy: 0.9005
Epoch 6/7
322/322 [==============================] - 26s 81ms/step - loss: 0.0366 - accuracy: 0.9864 - val_loss: 0.4696 - val_accuracy: 0.9002
Epoch 7/7
322/322 [==============================] - 26s 81ms/step - loss: 0.0315 - accuracy: 0.9894 - val_loss: 0.4714 - val_accuracy: 0.8999

## Test data

In [112]:
y_pred=model.predict_classes(X_test)
y_pred

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([[1],
       [0],
       [1],
       ...,
       [0],
       [1],
       [1]], dtype=int32)

In [113]:

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1755,  195],
       [ 148, 1328]])

In [114]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8998832457676591

In [115]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         0.0       0.92      0.90      0.91      1950
         1.0       0.87      0.90      0.89      1476

    accuracy                           0.90      3426
   macro avg       0.90      0.90      0.90      3426
weighted avg       0.90      0.90      0.90      3426

